name: android-ci

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

jobs:
  build:
    strategy:
      matrix:
        jdk:
         - '17'
        os:
          # - macos-latest
          # - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build init with Gradle
      run: ./gradlew clean buildEnvironment --warning-mode all
    - name: Build test with Gradle
      run: |
        ./gradlew plugin:test
        ./gradlew demo:test
    - name: Build test coverage with Gradle
      run: |
        ./gradlew plugin:jacocoDebugReport
    - name: Build assemble debug with Gradle
      run: |
        ./gradlew plugin:assembleDebug
        ./gradlew demo:assembleDebug
